# Generated by Django 4.0.6 on 2022-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('wifi', models.BooleanField(default=False, verbose_name='Наличие Wi-Fi')),
                ('comfortables', models.ManyToManyField(related_name='hotel_comfortables', to='main.comfortable', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
